=== Elizaveta99/JavaXMLParser/Collection.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="collection">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="name"/>
                <xs:sequence>
                    <xs:element name="weapon" type="weapon" minOccurs="0" maxOccurs="unbounded"></xs:element>
                </xs:sequence>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="weapon">
        <xs:sequence>
            <xs:element type="xs:string" name="type"/>
            <xs:element type="xs:string" name="title"/>
            <xs:element type="xs:double" name="price"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Elizaveta99/JavaXMLParser/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<collection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Collection.xsd">
    <name>Cold Steel Collection</name>
    <weapon>
        <type>Piercing</type>
        <title>rapier</title>
        <price>200.0</price>
    </weapon>
    <weapon>
        <type>Stabbing</type>
        <title>sword</title>
        <price>10.0</price>
    </weapon>
    <weapon>
        <type>Piercing</type>
        <title>spear</title>
        <price>100.0</price>
    </weapon>
    <weapon>
        <type>ShockFragmenting</type>
        <title>mace</title>
        <price>300.0</price>
    </weapon>
    <weapon>
        <type>Stabbing</type>
        <title>katana</title>
        <price>200.0</price>
    </weapon>
    <weapon>
        <type>Chopping</type>
        <title>tomahawk</title>
        <price>210.0</price>
    </weapon>
</collection>
